### ISSUE TITLE
GoCon公式サイトの差し替え

### ISSUE THREAD

**Issue by aimof** [GoCon/2019-Spring#2]
1. Merge #1
2. masterをfirebaseにデプロイ(__firebaseの権限が必要__)
3. PapperCallの https://gocon.jp を https://gocon.jp/pages/home に変更(権限が必要)
4. connpassの https://gocon.jp を https://gocon.jp/pages/home に変更(権限が必要)

**Comment by ymotongpoo** [comment]
@tenntenn @aimof と連携できる？もしくはFirebase Hostingの権限付与をお願いします！

**Comment by aimof** [comment]
権限を頂いたのでデプロイしますね
